FROM java:8

EXPOSE 8090

ADD /target/acme-message-web-restful-crud-0.0.1-SNAPSHOT.jar acme-message-web-restful-crud-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","acme-message-web-restful-crud-0.0.1-SNAPSHOT.jar"]