version: '3.7'
services:
   nginx_server:
      image: acme/acme-nginx
      ports:
       - '80:80'
      networks:
       - acme-network
      depends_on:
       - "acme-greeting-1"
       - "acme-greeting-2"
       - "acme-greeting-3"
    
   acme-greeting-1:
      image: acme/acme-greeting-api-restful-docker-nginx
      ports:
       - '8081:8091'
      networks:
       - acme-network

   acme-greeting-2:
      image: acme/acme-greeting-api-restful-docker-nginx
      ports:
       - '8082:8091'
      networks:
       - acme-network
       
   acme-greeting-3:
      image: acme/acme-greeting-api-restful-docker-nginx
      ports:
       - '8083:8091'
      networks:
       - acme-network

networks:
   acme-network:
      name: acme-network