version: '3.7'
services:
   nginx_server:
      container_name: nginx_server
      image: nginx:1.13
      restart: always
      ports:
      - 80:80
      - 443:443
      volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      depends_on:
      - app
    
   app:
      build: .
      volumes:
         - .:/app
         - ~/.m2:/root/.m2
      working_dir: /app
      command: mvn clean spring-boot:run -Pdev
      ports:
      - '8080:8091'
      networks:
      - acme-network


networks:
   acme-network:
      name: acme-network