#DEFAULT/DEV ENVIRONEMNT SETTING#

# *** Configuration SERVER ***
server:
   port: 8091
   servlet-path: /
   
# *** Configuration SPRING ***
spring:

   # *** Configuration General ***
   profiles:
      active: "@spring.profiles.active@"
   banner:
      location: classpath:custom-banner.txt
      
   # *** Configuration H2 ***
   h2:
      console:
         enabled : true
         
   # *** Configuration LiquiBase ***
   liquibase:
      enabled: true
      change-log: classpath:db/changelog/liquibase-changeLog.xml
      drop-first: true
      contexts:
   
   # *** Configuration Datasource ***
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true; #jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL;DATABASE_TO_UPPER=FALSE;
      # DATABASE_TO_UPPER=False presenta problemas
      username: sa
      password: sa
      drop-first: true
      default-schema: 
   
   # *** Configuration JPA ***
   jpa:
      hibernate:
         dialect: org.hibernate.dialect.H2Dialect
         show-sql: false
         hbm2ddl:
            auto: auto
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate:
            format_sql: false
            generate_statistics: false
   
# *** Configuration SECURITY ***
security:
   basic:
      enabled: false

# *** Configuration ACTUATORS ***
management:
   server:
      port: 8091         # Actuator port
   endpoint:             # Enabling Endpoints
      shutdown:
         enabled: true   # Configure "shutdown" enabled (By default all endpoints are enabled except shutdown) 
      info:
         enabled: true
   endpoints:
      web:
         base-path: /manage
         exposure:
            include: health, info, beans, shutdown # Include endpints in web mode
   security:
      enabled: false # management port is internal only. no need to secure it

# *** Configuration INFO ACTUATOR ***
info:
   app:
      artifact: "@project.artifactId@"
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
      java: "@java.version@"
      encoding: "@project.build.sourceEncoding@"
      environment: "DEFAULT/LOCAL"