#DEV ENVIRONEMNT SETTING#
server:
   port: 8091
   
spring:
   profiles:
      active: "@spring.profiles.active@"
   banner:
      location: classpath:custom-banner.txt
   data:
      web:
         pageable:
            default-page-size: 25
            max-page-size: 100
   h2:
      console:
         enabled : false
   liquibase:
      enabled: false
   jpa:
      database: SQL_SERVER
      hibernate:
         dialect: org.hibernate.dialect.SQLServer2012Dialect
         show-sql: true
         hbm2ddl:
            auto: none
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate:
            format_sql: false
            generate_statistics: false
   datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost;databaseName=DAE
      username: SA
      password: CistecDaepass1.
      drop-first: false
      default-schema: dbo

security:
   basic:
      enabled: false

management:
   server:
      port: 8091        # Actuator port
   endpoint:             # Enabling Endpoints
      shutdown:
         enabled: true   # Configure "shutdown" enabled (By default all endpoints are enabled except shutdown) 
      info:
         enabled: true
   endpoints:
      web:
         base-path: /manage
         exposure:
            include: health, info, beans, shutdown # Include endpints in web mode
   security:
      enabled: false # management port is internal only. no need to secure it 

#Swagger info
swagger:
   info:
      title: CRUD Company API
      description: Company API Description
      produce-consume: application/json
      version: 1.0
      terms: urn:tos
      contact:
         name: Cistec
         url: https://www.cistec.es
         email: global@acme.corp.com
      license: Apache 2.0
      license-url: http://www.apache.org/licenses/LICENSE-2.0

info:
   app:
      artifact: "@project.artifactId@"
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
      java: "@java.version@"
      encoding: "@project.build.sourceEncoding@"
      environtment: "DEV"