server:
   port: 8091
   
spring:
   profiles:
      active: dev
   banner:
      location: classpath:custom-banner.txt
  
#Management Endpoints 
management:
   server:
      port: 8091         # Actuator port
   endpoint:             # Enabling Endpoints
      shutdown:
         enabled: true   # Configure "shutdown" enabled (By default all endpoints are enabled except shutdown) 
      info:
         enabled: true
   endpoints:
      web:
         base-path: /manage
         exposure:
            include: health, info, beans, shutdown # Include endpints in web mode
   security:
      enabled: false # management port is internal only. no need to secure it
  
info:
   app:
      artifact: @project.artifactId@
      name: @project.name@
      description: @project.description@
      version: @project.version@
      java: @java.version@
      encoding: @project.build.sourceEncoding@
      
security:
   basic:
      enabled: false
   oauth2:
      client:
         client-id: 7a2DIMEBEY2CIsoJj66mil6VK5sa
         client-secret: YiJDmCN3nYCXtfT2kEYtXEOR9g8a
         client.access-token-uri: https://localhost:9443/oauth2/token
         user-authorization-uri: https://localhost:9443/oauth2/token/authorize
         scope: openid
      resource:
         filter-order: 3
         user-info-uri: https://localhost:9443/oauth2/userinfo
         token-info-uri: https://localhost:9443/oauth2/introspect
         prefer-token-info: true