#  DESCRIPTION
#   * Multi-Stage
#   * Aproach : BUILD and RUNTIME 
#   * Use a optimized image
#   * Best Practices Build
#   * Copy over the built artifact from the build image

# BUILD Stage

FROM maven:3.6.3-openjdk-8-slim as build

COPY ./pom.xml ./pom.xml

RUN mvn dependency:go-offline -B

COPY ./src ./src

RUN mvn package



# RUNTIME Stage

FROM openjdk:8-jdk-alpine

WORKDIR /service

COPY --from=build target/acme-greeting-api-restful-*.jar ./

ENTRYPOINT ["java","-jar","./target/acme-greeting-api-restful-0.0.1-SNAPSHOT.jar"]

EXPOSE 8091