#  DESCRIPTION
#   * Multi-Stage
#   * Aproach : BUILD and RUNTIME
#   * Use a optimized image
#   * Best Practices Build
#   * Copy over the built artifact from the build image

# BUILD Stage

# Pull official base image
FROM maven:3.5-jdk-8 as build

COPY src /usr/src/myapp/src
COPY pom.xml /usr/src/myapp
RUN mvn -f /usr/src/myapp/pom.xml clean package



# RUNTIME Stage

FROM openjdk:8-jre-alpine

WORKDIR /service

COPY --from=build target/acme-greeting-api-restful-*.jar ./

ENTRYPOINT ["java","-jar","./target/acme-greeting-api-restful-0.0.1-SNAPSHOT.jar"]

EXPOSE 8091